package com.example.calc.calculation;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.Instant;

/**
 * 計算 1 件を表す Model クラス（JPA エンティティ）。DB の {@code calculations} テーブル 1 行に対応する。
 *
 * <p>LEARN: エンティティは「DB の 1 行を Java のオブジェクトとして表したもの」。DTO との違いが要点:
 *
 * <ul>
 *   <li>DTO は不変（{@code record}）で、層の境界を越えるための入れ物。API の契約そのもの。
 *   <li>エンティティは可変（フィールドを書き換えると UPDATE 文になる）で、DB のスキーマに縛られる。
 * </ul>
 *
 * <p>LEARN: だからエンティティを API のレスポンスとして直接返してはいけない（不変条件 #3）。 返すと「DB のカラムを増やしただけで API の契約が変わる」状態になり、
 * さらに内部だけで使いたい列まで外に漏れる。変換は {@link CalculationMapper} が担当する。
 *
 * <p>LEARN: JPA の要求でデフォルトコンストラクタ（引数なし）が必須。Hibernate が DB から 行を読むときにリフレクションで空のインスタンスを作り、あとから値を詰めるため。
 * 外部から使わせたくないので {@code protected} にしておく。
 */
@Entity
@Table(name = "calculations")
public class Calculation {

  /**
   * 主キー。DB が採番する。
   *
   * <p>LEARN: {@code GenerationType.IDENTITY} は「DB の自動採番列（PostgreSQL の {@code BIGSERIAL} / {@code
   * GENERATED BY DEFAULT AS IDENTITY}）に任せる」という指定。 採番が確定するのは INSERT の瞬間なので、{@code save()} 前は {@code
   * null}。 「id が null かどうか」が新規か既存かの判定になる。
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /**
   * 左オペランド。
   *
   * <p>LEARN: カラム名を {@code left_operand} にしているのは、{@code left} / {@code right} が SQL の 予約語（{@code
   * LEFT JOIN} の LEFT）で、そのまま使うと DB によってはエラーになるため。 「Java のフィールド名 = DB のカラム名」が常に成り立つわけではない、という例。
   *
   * <p>LEARN: {@code precision} / {@code scale} は {@code NUMERIC(38, 10)} を意味する。 金額や計算結果を {@code
   * double} ではなく {@code NUMERIC} で持つのは、DTO で {@link BigDecimal} を 使うのと同じ理由（二進浮動小数点の誤差を持ち込まない）。
   */
  @Column(name = "left_operand", nullable = false, precision = 38, scale = 10)
  private BigDecimal leftOperand;

  /**
   * 演算子。
   *
   * <p>LEARN: {@code @Enumerated(EnumType.STRING)} で {@code 'ADD'} という文字列として保存する。 既定の {@code
   * ORDINAL}（0,1,2…の連番）は、enum の定義順を入れ替えた瞬間に 既存データの意味が変わる地雷なので使わない。ここは実務でも事故が多い。
   */
  @Enumerated(EnumType.STRING)
  @Column(nullable = false, length = 16)
  private Operator operator;

  @Column(name = "right_operand", nullable = false, precision = 38, scale = 10)
  private BigDecimal rightOperand;

  @Column(nullable = false, precision = 38, scale = 10)
  private BigDecimal result;

  /** 利用者が後から付けるメモ。PATCH で更新する対象。未設定なら {@code null}。 */
  @Column(length = 200)
  private String memo;

  /** 作成時刻。{@link #onCreate()} が入れる。 */
  @Column(name = "created_at", nullable = false, updatable = false)
  private Instant createdAt;

  /** 最終更新時刻。{@link #onUpdate()} が入れる。 */
  @Column(name = "updated_at", nullable = false)
  private Instant updatedAt;

  /** JPA 用。アプリコードからは使わない。 */
  protected Calculation() {}

  public Calculation(
      BigDecimal leftOperand, Operator operator, BigDecimal rightOperand, BigDecimal result) {
    this.leftOperand = leftOperand;
    this.operator = operator;
    this.rightOperand = rightOperand;
    this.result = result;
  }

  /**
   * INSERT の直前に Hibernate が呼ぶ。
   *
   * <p>LEARN: {@code @PrePersist} / {@code @PreUpdate} は JPA のライフサイクルコールバック。
   * 「保存するたびに必ず時刻を入れたい」ような処理を Service 側に散らさず、エンティティに寄せられる。 呼び忘れが起きないのが利点（Spring Data の
   * {@code @CreatedDate} でも同じことができる）。
   */
  @PrePersist
  void onCreate() {
    Instant now = Instant.now();
    this.createdAt = now;
    this.updatedAt = now;
    System.out.printf(
        "[4/5 保存] INSERT する直前(id はまだ null): %s %s %s%n", leftOperand, operator, rightOperand);
  }

  /** UPDATE の直前に Hibernate が呼ぶ。 */
  @PreUpdate
  void onUpdate() {
    this.updatedAt = Instant.now();
    System.out.printf("[4/5 保存] UPDATE する直前: id=%s%n", id);
  }

  /**
   * 式（左・演算子・右）を差し替え、結果を入れ直す。PUT（全置換）で使う。
   *
   * <p>LEARN: setter を並べるのではなく「何をする操作か」で名前を付けたメソッドを置く。
   * こうするとエンティティが「どう変わりうるか」を自分で決められる（不正な状態になりにくい）。
   */
  void replaceExpression(
      BigDecimal leftOperand, Operator operator, BigDecimal rightOperand, BigDecimal result) {
    this.leftOperand = leftOperand;
    this.operator = operator;
    this.rightOperand = rightOperand;
    this.result = result;
  }

  void changeMemo(String memo) {
    this.memo = memo;
  }

  public Long getId() {
    return id;
  }

  public BigDecimal getLeftOperand() {
    return leftOperand;
  }

  public Operator getOperator() {
    return operator;
  }

  public BigDecimal getRightOperand() {
    return rightOperand;
  }

  public BigDecimal getResult() {
    return result;
  }

  public String getMemo() {
    return memo;
  }

  public Instant getCreatedAt() {
    return createdAt;
  }

  public Instant getUpdatedAt() {
    return updatedAt;
  }
}
