-- Sprint 1: 最初のスキーマ。users 1-* categories / users 1-* tasks / categories 1-* tasks(NULL可)

create table users (
    id           bigint generated by default as identity primary key,
    email        varchar(255) not null unique,
    password     varchar(255) not null,
    display_name varchar(100) not null,
    role         varchar(20)  not null,
    created_at   timestamptz  not null,
    updated_at   timestamptz  not null
);

create table categories (
    id         bigint generated by default as identity primary key,
    name       varchar(50) not null,
    color      varchar(7),
    owner_id   bigint      not null references users (id),
    created_at timestamptz not null,
    updated_at timestamptz not null,
    -- 複合ユニーク: 同じユーザーが同名カテゴリを2つ持てない
    constraint uq_categories_owner_name unique (owner_id, name)
);
create index idx_categories_owner on categories (owner_id);

create table tasks (
    id           bigint generated by default as identity primary key,
    title        varchar(200) not null,
    description  varchar(2000),
    status       varchar(20)  not null,
    priority     varchar(10),
    due_date     date,
    -- カテゴリ削除時はタスクを消さず category_id を NULL にする(DB 側で担保)
    category_id  bigint references categories (id) on delete set null,
    owner_id     bigint       not null references users (id),
    created_at   timestamptz  not null,
    updated_at   timestamptz  not null,
    completed_at timestamptz
);
create index idx_tasks_owner on tasks (owner_id);
create index idx_tasks_category on tasks (category_id);
create index idx_tasks_status on tasks (status);
